<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RuntimeIdentifier Condition="'$(Portable)' == 'true'">win-x64</RuntimeIdentifier>
    <SelfContained Condition="'$(Portable)' == 'true'">true</SelfContained>
    <PublishSingleFile Condition="'$(Portable)' == 'true'">false</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract Condition="'$(Portable)' == 'true'">false</IncludeNativeLibrariesForSelfExtract>
    <DebugType Condition="'$(Portable)' == 'true'">None</DebugType>
    <DebugSymbols Condition="'$(Portable)' == 'true'">false</DebugSymbols>
  </PropertyGroup>
</Project>

